spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=Oracle
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop